In [16]:
from pandas import DataFrame
import pandas as pd
import numpy as np

In [17]:
from jsonapi_client import Session, Filter
import pycurl

API_BASE = 'https://www.ebi.ac.uk/metagenomics/api/latest/'

In [18]:
# 'studies' bisa diganti dengan target semisal 'sample' ; 'MGYS00001939' merupakan accession
with Session(API_BASE) as s:
    std = s.get('studies', 'MGYS00001939').resource

In [19]:
#memunculkan study_name
std

In [114]:
#melihat jumlah sample pada study di atas
x = std.samples
x = x[0]
x.sample_name

'Bulk soil exposed to nanosilver, sample 2'

In [119]:
with Session(API_BASE) as s:
    std = s.get('studies', 'MGYS00001939').resource
print(std.accession)
sample = std.samples
#melihat informasi pada salah satu sample yang dipilih
df = pd.DataFrame([])
acc = []
sample_name = []
for x in sample:
    acc.append(x.accession)
    sample_name.append(x.sample_name)
    meta = x.sample_metadata
    meta = pd.DataFrame.from_dict(meta)
    meta = meta.set_index('key') 
    meta = meta.drop(columns='unit')
    meta = meta.transpose()
    df = df.append(meta)
acc = pd.DataFrame(acc, columns=['Accession'])
sample_name = pd.DataFrame(sample_name, columns=['Sample Name'])
df = df.reset_index()
df = df.drop(columns='index')
merged = acc.merge(sample_name, left_index=True, right_index=True, how='inner')
merged = merged.merge(df, left_index=True, right_index=True, how='inner')
merged

MGYS00001939

,Accession,Sample Name,investigation type,geographic location (longitude),"geographic location (country and/or sea,region)",collection date,environment (biome),environment (feature),environment (material),environmental package,sequencing method,elevation,geographic location (latitude),instrument model
0,ERS1851088,"Bulk soil exposed to nanosilver, sample 2",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
1,ERS1851084,"Bulk soil not exposed to nanosilver, sample 1",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
2,ERS1851093,"Rhizosphere soil exposed to nanosilver, sample 1",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
3,ERS1851087,"Bulk soil exposed to nanosilver, sample 1",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
4,ERS1851094,"Rhizosphere soil exposed to nanosilver, sample 2",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
5,ERS1851086,"Bulk soil not exposed to nanosilver, sample 3",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
6,ERS1851095,"Rhizosphere soil exposed to nanosilver, sample 3",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
7,ERS1851090,"Rhizosphere soil not exposed to nanosilver, sa...",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
8,ERS1851092,"Rhizosphere soil not exposed to nanosilver, sa...",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
9,ERS1851085,"Bulk soil not exposed to nanosilver, sample 2",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
10,ERS1851091,"Rhizosphere soil not exposed to nanosilver, sa...",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000
11,ERS1851089,"Bulk soil exposed to nanosilver, sample 3",metatranscriptome,5.411394,Belgium,2015-03-18,area of cropland,area of cropland,agricultural soil,soil,Illumina,46.0,50.93487,Illumina HiSeq 4000

In [128]:
for a in x.runs:
    for b in a.analyses:
        for c in b.downloads:
            print(c.url)

https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_1.fasta.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_2.fasta.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_3.fasta.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_CDS_annotated.faa.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_CDS_unannotated.faa.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_interproscan.fasta.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_noFunction.fasta.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_ORF_unannotated.ffn.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_readsWithpCDS.fasta.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_GO_slim.csv
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_GO.csv
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_InterPro.tsv.gz
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_16SrRNA.fasta
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_23SrRNA.fasta
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_5SrRNA.fasta
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_otu_table_hdf5.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_otu.tsv
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_pruned.tree
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_tRNA.fasta

In [65]:
blank = []
for x in sample:
    #print(x.sample_metadata)
    df = pd.DataFrame(x.sample_metadata)
    #print(df)
    index = np.where(df['key'].str.contains('location'))[0]
    blank.append(df.iloc[index, :])
    index = np.where(df['key'].str.contains('biome'))[0]
    blank.append(df.iloc[index, :])
    index = np.where(df['key'].str.contains('elevation'))[0]
    blank.append(df.iloc[index, :])
    df_new = pd.concat(blank)
df_new

                                                key  unit             value
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0

In [43]:
sample = x.sample_metadata
index = np.where(df['key'].str.contains('location'))[0]
for i in index:
    print(sample[i]['key'])
    print(sample[i]['value'])

geographic location (longitude)
5.411394
geographic location (country and/or sea,region)
Belgium
geographic location (latitude)
50.93487

ValueError: If using all scalar values, you must pass an index

In [14]:
#memasukkan sample yang dipilih ke bentuk kolom
df = pd.DataFrame(sample[0].sample_metadata)
df

NameError: name 'sample' is not defined

In [19]:
blank = []

In [20]:
#membuat index baru dari list 'key' yang dipilih
index = np.where(df['key'].str.contains('location'))[0]
blank.append(df.iloc[index, :])
index = np.where(df['key'].str.contains('biome'))[0]
blank.append(df.iloc[index, :])
index = np.where(df['key'].str.contains('elevation'))[0]
blank.append(df.iloc[index, :])

In [21]:
#'key' yang dilih dijadikan data frame baru
df_new = pd.concat(blank)
df_new

                                                key  unit             value
1                   geographic location (longitude)  None          5.411394
2   geographic location (country and/or sea,region)  None           Belgium
10                   geographic location (latitude)  None          50.93487
4                               environment (biome)  None  area of cropland
9                                         elevation  None              46.0

In [8]:
filename_sample = ''

In [27]:
#membuat loop accession di dalam bentuk list
for i in sample:
    #print('sample: '+str(i.accession))
    for x in i.runs:
        #print('runs: '+str(x.accession))
        for y in x.analyses:
            #print('analyses: '+str(y.accession))
            for z in y.downloads:
                if 'json.biom' in z.url:
                    print(z.url)

https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135103/file/ERR2061845_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135102/file/ERR2061841_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135099/file/ERR2061850_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135098/file/ERR2061844_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135093/file/ERR2061851_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135104/file/ERR2061843_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135094/file/ERR2061852_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135095/file/ERR2061847_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135096/file/ERR2061849_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135100/file/ERR2061842_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135101/file/ERR2061848_MERGED_FASTQ_otu_table_json.biom
https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00135097/file/ERR2061846_MERGED_FASTQ_otu_table_json.biom

In [5]:
#membuat folder
from pathlib import Path
import os
Study = 'MGYS00001939'
_dir = os.getcwd()#'D:\\Seminar\\Seminar_Anam'
print(_dir)
_dir = os.path.join(_dir, 'Study%s' % Study)
if not os.path.exists(_dir):
    os.makedirs(_dir)
#%rmdir(Study+str)
#with open('_dir'+i.accession+'.biom', 'wb') as f:
    #c = pycurl.Curl()
    #c.setopt(c.URL, z.url)
    #c.setopt(c.WRITEDATA, f)
    #c.perform()
#c.close()

E:\Jupyter_Lab\Seminar_Anam